# Generated by Django 5.2.8 on 2026-07-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
