# Generated by Django 6.0.7 on 2026-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_appointment_time_appointment_time_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='treatment_plan',
            new_name='prescription',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, help_text="Additional notes or doctor's remarks", null=True),
        ),
    ]
