# Generated by Django 6.0.7 on 2026-07-13 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='afternoon_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='afternoon_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='afternoon_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='morning_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='morning_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='morning_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='main.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('OFF', 'Day Off'), ('TRAVEL', 'Travel'), ('LEAVE', 'Leave'), ('CUSTOM', 'Custom Schedule')], max_length=20)),
                ('morning_available', models.BooleanField(default=False)),
                ('afternoon_available', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='main.doctor')),
            ],
        ),
    ]
