# Generated by Django 6.0.7 on 2026-07-13 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_doctorschedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Whole Day'), ('MORNING', 'Morning Only'), ('AFTERNOON', 'Afternoon Only'), ('OFF', 'Unavailable')], max_length=20)),
                ('morning_start', models.TimeField(blank=True, null=True)),
                ('morning_end', models.TimeField(blank=True, null=True)),
                ('afternoon_start', models.TimeField(blank=True, null=True)),
                ('afternoon_end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_schedule', to='main.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorScheduleException',
        ),
    ]
