# Generated by Django 6.0.7 on 2026-07-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_doctordateschedule_delete_doctorscheduleexception'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
